language: minimal
os: linux
dist: bionic

addons:
  apt:
    packages:
    - doxygen
    - graphviz
    - clang

script:
- doxygen Doxyfile
- make -C tests

deploy:
  provider: pages:git
  token: $GITHUB_TOKEN
  edge: true
  local_dir: doxygen/html
  on:
    branch: master

